// Code generated by scripts/sync-brand-web.mjs. DO NOT EDIT.

package main

const brandName = "mu"
const brandHost = "mu.social"
const brandHomeURL = "https://mu.social"
const brandSocialCardURL = "https://mu.social/static/social-card-default-gradient.png"
const brandEmbedService = "https://embed.bsky.app"
